version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    networks:
      - bk
    ports:
      - "27018:27017"
    env_file:
      - ./db/.env
      - ./mongo-express/.env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./books.json:/books.json

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    networks:
      - bk
    env_file:
      - ./db/.env
      - ./mongo-express/.env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
  
  app:
    build: ./book-service/
    container_name: app_container
    networks:
      - bk
    environment:
      MONGO_URI: mongodb://db:27017/library
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  bk:
    driver: bridge
